---
title: 'Milestone #2'
author: "Dominic Skinnion"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Final Project #1: Nicolas Cage: an In-Depth Analysis by Claire Fridkin

  This project really intrigued me. As a Nicolas Cage meme-enthusiast, I could not resist checking out this project. The first thing that really strikes me is the depth of data that was collected for this project. In the first part of the project "Movie Textual Analysis," there are ten movies from which Claire analyzed the scripts. For each script, she tallied the utterances of each word in the script and plotted the 10 most used negative and positive words. She also made a bar plot with the distribution of negative and positive word scores with their number of utterences and a plot of runtime vs. the positivity or negativity of expression. I really like the use of colors that she chose for this plot because it shows the range of expression. In the second part of her analysis, she divides all of his movies by their MPAA ratings, and evaluates variables such as number of movies, box office revenue, release date, critic scores, and average word sentiment. Again, her use of colors really stands out as a pro to this project. If I had to pick one thing that I would change, I think the average word sentiment by MPAA rating plot would be better served as something other than a boxplot, because as she notes, there were only 10 movies used for the 3 plots, which seems a little low (However, she acknowledges this in her caption). Overall, there are not many cons for me to describe. She did a really great job, and the plots' colors made them very easy to interpret.
  
  
  
Final Project #2: Julian Edelman Total Yards Depending on Opponent by Alex LaPolice

As a Massachusetts native, of course I love Julian Edelman -- so, naturally, I picked this project to look into. There isn't too much going on with this project, although there are a couple of cool functions that I like. For one, I like the way that you can select a team from a drop down menu, and the plot changes to match your selection. I also like how the graphs are simple. On the other hand, the graphs may be a bit too simple. They are simply scatterplots of Edelman's yards over time. Considering the fact that the Patriots don't play the same teams every year, there are some gaps in the data for each time. This doesn't paticularly look good when each plot only contains one team, and there are only two data points. If I were to make a suggestion, I would say that there could have been plots of teams in each division, color coded by team. There also could have been a plot of all teams, color coded by team or division. I also think it would have been cool to see the relationship between his yards and his age or time in the NFL. Perhaps a linear regression could have been used, or a smooth line, just so that the data could be interpretted over time easier. 